### ISSUE TITLE
Python 2 dynamic load zlib segfault or inconsistent stream state

### ISSUE THREAD

**Issue by EricR86** [conda-forge/pytables-feedstock#29]
I believe this is related to Issue #27.

From a `conda --create tablestest python=2 pytables` I can faithfully reproduce a segmentation fault or exception with the following python snippet:

```python
from tables import Filters
import gzip

with gzip.open('somefile.gz') as agp_file:
    print agp_file.readlines()
```
Where 'somefile.gz' is any gzipped file.

This segfaults or produces the following traceback:
```python
Traceback (most recent call last):
  File "./gzip_open_test.py", line 6, in <module>
    print agp_file.readlines()
  File "/scratch/miniconda2/envs/tablestest/lib/python2.7/gzip.py", line 464, in readline
    c = self.read(readsize)
  File "/scratch/miniconda2/envs/tablestest/lib/python2.7/gzip.py", line 268, in read
    self._read(readsize)
  File "/scratch/miniconda2/envs/tablestest/lib/python2.7/gzip.py", line 319, in _read
    uncompress = self.decompress.decompress(buf)
zlib.error: Error -2 while decompressing: inconsistent stream state
```

If you swap the order of the imports, or remove the `tables` import, the error no longer exists. I believe it's likely some sort of dynamic shared object loading conflict and I'm currently trying to track it down.

**Comment by scopatz** [comment]
@avalentino - I think we already are doing that. See https://github.com/conda-forge/pytables-feedstock/blob/master/recipe/meta.yaml#L34

**Comment by tomkooij** [comment]
@scopatz No, we need to uncomment and use the "external" blosc. I'll whip up a PR :-)

**Comment by scopatz** [comment]
Oh haha, I misunderstood what "packaged" meant @tomkooij  ;)

**Comment by avalentino** [comment]
> Oh haha, I misunderstood what "packaged" meant @tomkooij ;)

yes, "packaged version of blosc " is the conda package of blosc. :)
Sorry for making confusion

**Comment by tomkooij** [comment]
The fix is merged. The new packages (build 8) should be in the conda-forge channel once the CIs finish building.
