### ISSUE TITLE
ImportError: Could not load hdf5.dll on python 3.8

### ISSUE THREAD

**Issue by adament** [conda-forge/pytables-feedstock#60]
Issue:
With a clean environment with python 3.8, hdf5 1.10.5 and pytables 3.6.1 on Windows I get "ImportError: Could not load any of ['hdf5.dll', 'hdf5dll.dll', 'pytables_hdf5.dll'], please ensure that it is installed in the package folder." when importing pytables.

```
Python 3.8.1 | packaged by conda-forge | (default, Jan  5 2020, 20:17:16) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tables
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Code\miniconda3\envs\pytables_test\lib\site-packages\tables\__init__.py", line 82, in <module>
    raise ImportError(
ImportError: Could not load any of ['hdf5.dll', 'hdf5dll.dll', 'pytables_hdf5.dll'], please ensure that it is installed in the package folder.
```

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at C:\Code\miniconda3\envs\pytables_test:
#
# Name                    Version                   Build  Channel
blosc                     1.17.0               h6538335_1    conda-forge
bzip2                     1.0.8                hfa6e2cd_2    conda-forge
ca-certificates           2019.11.28           hecc5488_0    conda-forge
certifi                   2019.11.28               py38_0    conda-forge
hdf5                      1.10.5          nompi_ha405e13_1104    conda-forge
intel-openmp              2019.4                      245
libblas                   3.8.0                    14_mkl    conda-forge
libcblas                  3.8.0                    14_mkl    conda-forge
liblapack                 3.8.0                    14_mkl    conda-forge
mkl                       2019.4                      245
mock                      3.0.5                    py38_0    conda-forge
numexpr                   2.7.1            py38h6538335_0    conda-forge
numpy                     1.17.3           py38hc71023c_0    conda-forge
openssl                   1.1.1d               hfa6e2cd_0    conda-forge
pip                       19.3.1                   py38_0    conda-forge
pytables                  3.6.1            py38h26f9782_0    conda-forge
python                    3.8.1                he1f5543_1    conda-forge
setuptools                45.0.0                   py38_1    conda-forge
six                       1.13.0                   py38_0    conda-forge
sqlite                    3.30.1               hfa6e2cd_0    conda-forge
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.16.27012          hf0eaf9b_1
wheel                     0.33.6                   py38_0    conda-forge
wincertstore              0.2                   py38_1003    conda-forge
zlib                      1.2.11            h2fa13f4_1006    conda-forge

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

     active environment : pytables_test
    active env location : C:\Code\miniconda3\envs\pytables_test
            shell level : 2
       user config file : C:\Users\aen\.condarc
 populated config files : C:\Users\aen\.condarc
          conda version : 4.8.0
    conda-build version : 3.18.11
         python version : 3.7.6.final.0
       virtual packages : __cuda=8.0
       base environment : C:\Code\miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Code\miniconda3\pkgs
                          C:\Users\aen\.conda\pkgs
                          C:\Users\aen\AppData\Local\conda\conda\pkgs
       envs directories : C:\Code\miniconda3\envs
                          C:\Users\aen\.conda\envs
                          C:\Users\aen\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.8.0 requests/2.22.0 CPython/3.7.6 Windows/10 Windows/10.0.16299
          administrator : False
             netrc file : None
           offline mode : False

```
</details>

**Comment by scopatz** [comment]
Hmm thanks for reporting @adament. @tomkooij any ideas?

**Comment by tomkooij** [comment]
I can reproduce this. This package is broken in a `python 3.8.1` conda env, whilst an identical env with `python 3.7.6` works.

As pointed out in: https://github.com/PyTables/PyTables/issues/779#issuecomment-562510531 Installing pytables using `pip install tables` in the same python 3.8 env does work: The same code, works (but pip installs a wheels with a self-compiled version of the HDF5 lib, with zlib statically linked)

Altough the logic of finding DLLs was changed in Python 3.8, that does not seem to be the problem here, as the location of the library is exactly the same for the conda-forge package and the wheel. (`Lib/site-packages/tables`)

It seems to be an actual problem with importing the conda-forge built `hdf5.dll`. In **every single** issue in the upstream PyTables package this has always been a problem with `zlib.dll` not found/incorrect.

Trying to manually import all the .DLLs in the `tables` package folder:
```
>>> ctypes.cdll.LoadLibrary(os.path.join('D:\Miniconda3\envs\py38\Lib\site-packages\\tables', 'blosc.dll'))
<CDLL 'D:\Miniconda3\envs\py38\Lib\site-packages\tables\blosc.dll', handle 7ffd87ea0000 at 0x1efd06778e0>
>>> ctypes.cdll.LoadLibrary(os.path.join('D:\Miniconda3\envs\py38\Lib\site-packages\\tables', 'bzip2.dll'))
<CDLL 'D:\Miniconda3\envs\py38\Lib\site-packages\tables\bzip2.dll', handle 7ffd90a70000 at 0x1efd0677640>
>>> ctypes.cdll.LoadLibrary(os.path.join('D:\Miniconda3\envs\py38\Lib\site-packages\\tables', 'hdf5.dll'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "d:\Miniconda3\envs\py38\lib\ctypes\__init__.py", line 451, in LoadLibrary
    return self._dlltype(name)
  File "d:\Miniconda3\envs\py38\lib\ctypes\__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'D:\Miniconda3\envs\py38\Lib\site-packages\tables\hdf5.dll'. Try using the full path with constructor syntax.
>>>

**Comment by tomkooij** [comment]
This needs a fix (revert of some commit) in PyTables `setup.py`... 

I can do that, but it might take a few days.

**Comment by tomkooij** [comment]
I investigated some more:
 - There are `.dll` files in `\lib\site-packages\tables`. IMO, DLLs should not be in the package folder in a conda env.
- Removing the DLLs from the package folder *AND* removing the code in `__init__.py` that tries to locate the DLL fixes this.

I can remove the code from `__init__.py` either in a patch for conda-forge or in the upstream repo. (I favour the latter).

But I wonder why the DLLs end up in de package folder during the build... Is it because the DLLs are in `data_files=[...]' in PyTables `setup.py` instead of `package_data=[...]` ???
@scopatz @ocefpaf ?

**Comment by adament** [comment]
Thank you very much!
